FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /src
COPY ["NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj", "NugetDotnetRestoreTest/"]
#RUN dotnet restore --verbosity detailed "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"
